export const CATALOG_FETCH_REQUEST = 'CATALOG_FETCH_REQUEST';
export const CATALOG_FETCH_SUCCESS = 'CATALOG_FETCH_SUCCESS';
export const CATALOG_FETCH_ERROR = 'CATALOG_FETCH_ERROR';

export const CATALOG_SET_CATEGORY = 'CATALOG_SET_CATEGORY';
export const CATALOG_RESET_CATEGORY = 'CATALOG_RESET_CATEGORY';